project:
  type: book
  output-dir: docs
  resources: 
  - "images/*"
  - "data/*"

book:
  title: "30DMC (2022)"
  author: "Lisa DeBruine"
  description: "Code and charts for the 2022 30-Day Map Challenge"
  cover-image: images/logos/logo.png
  image: images/logos/logo.png
  fav-icon: images/logos/favicon.ico
  #cookie-consent: true
  google-analytics: "G-6NP3MF25W3"
  page-navigation: true
  search: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  repo-url: https://github.com/debruine/30DMC-2022/
  repo-branch: master
  repo-actions: [edit, issue, source]
#  downloads: [pdf, epub]
  sharing: [twitter, facebook, linkedin]
  # sidebar:
  #   style: docked
  #   background: light
  page-footer: 
    left: "CC-BY 2022, Lisa DeBruine" 
    right: 
      - icon: github
        href: https://github.com/debruine/30DMC-2022
      - icon: mastodon 
        href: https://tech.lgbt/@debruine
  chapters:
    - index.qmd
    - 01-points.qmd

bibliography: include/book.bib
csl: include/apa.csl

format:
  html:
    theme: 
      light: yeti
      dark: darkly
    code-link: true
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    code-copy: true
    # code-block-border-left: "#4864DB"
    highlight-style: a11y
    # monofont: Fira Code
    # mainfont: Open Sans
    css: include/style.css
    include-after-body: include/script.js



